### ISSUE TITLE
Game was not updated

### ISSUE THREAD

**Issue by Bull3tSp33d** [dbuteau/games-matcher#14]
When using "$import steam <steamID64>" it stops at 29 processed games, and says "starbound - game was not updated"

I have run the command a few times, and always get stuck on Starbound. 
![Capture](https://user-images.githubusercontent.com/62156279/144901941-562e71a2-0cd9-4bb1-aac1-f6c4945e9152.PNG)

**Comment by dbuteau** [comment]
Hello,
this means that the STEAM API did not respond with the expected informations and the bot don't know what to do.
Have to check what the api answer to manage this use case

**Comment by dbuteau** [comment]
it's depend of game, i've seen than somes have changed of id between your library(when you bought it) and the api now.
The api don't have search functions for title, so i have to update id manually.

Now the bot will not stop anymore if it encounter this kind of problem, it just log the problematic game for me and continue to parse your lib.
